### ISSUE TITLE
[移动端] 绕过 移动端浏览器 广告移除 ad block

### ISSUE THREAD

**Issue by hudk114** [hudk114/front-end#4]
# 问题
移动端开发，QQ浏览器和UC浏览器开启了广告过滤模式时，广告图片无法加载

DOM结构
```html
<div node-type="module-index-ad" class="module-index-ad">
  <div class="ad-wrapper">
    <a href="https://www.uoolu.com/zhuanti/PIN1000/?uoolu=souhu"
      target="_blank">
      <img class="ad-img"
        src="/module/index-ad/img/ad.png"
        alt="" />
    </a>
  </div>
</div>
```
style
```css
.module-index-ad {
  margin-bottom: 10px;
  background-color: $color-white;

  .ad-wrapper {
    box-sizing: border-box;
    padding: 0 15px;
    width: 100%;

    .ad-img {
      width: 100%;
      border-radius: 4px;
    }
  }
}
```

**Comment by hudk114** [comment]
# 解决方案
广告的拦截一般采用两种方式
1. 结构判断，在css和html中，如果class或者id含有明确的ad或者advertise，会被判断为广告
1. 对url(href, src)进行判断，如果是广告列表库中的就判断为广告进行拦截

所以，将html和css中所有的ad都去掉，基本就可以防止被拦截

_虽然这样其实很没有节操_

DOM结构
```html
<div node-type="module-index-asdfasfa" class="module-index-asdfasfa">
  <div class="asdfasfa-wrapper">
    <a href="https://www.uoolu.com/zhuanti/PIN1000/?uoolu=souhu"
      target="_blank">
      <img class="asdfasfa-img"
        src="/module/index-asdfasfa/img/asdfasfa.png"
        alt="" />
    </a>
  </div>
</div>
```
style
```css
.module-index-asdfasfa {
  margin-bottom: 10px;
  background-color: $color-white;

  .asdfasfa-wrapper {
    box-sizing: border-box;
    padding: 0 15px;
    width: 100%;

    .asdfasfa-img {
      width: 100%;
      border-radius: 4px;
    }
  }
}
```
